### ISSUE TITLE
Cierre del juego en pantalla de carga del primer nivel

### ISSUE THREAD

**Issue by GrimGreenEyes** [GrimGreenEyes/Programming-Departament#10]
Impacto: crítico

Entorno: ordenador de sobremesa, google chrome

Descripción: tras avanzar en el mapa al primer nivel, la pantalla de carga se ha congelado y ha aparecido una notificación de error de javascript. Este error además obliga a recargar la página, perdiendo así todo el progreso de la partida.

Como reproducir el error: iniciar un nivel

Imagen:
![image](https://user-images.githubusercontent.com/114918948/204153789-2a63a188-e7d8-4fac-a574-931a12c1f3e6.png)

**Comment by GrimGreenEyes** [comment]
Error al crear el grid

**Comment by dieguoin** [comment]
Fixed
