### ISSUE TITLE
Personaje se mueve al mover la vista del tablero

### ISSUE THREAD

**Issue by GrimGreenEyes** [GrimGreenEyes/Programming-Departament#11]
Impacto: medio

Entorno: ordenador de sobremesa, google chrome

Descripción: al intentar mover el tablero haciendo click en una casilla sobre la que puedes avanzar, el personaje avanza hacia ella

Como reproducir el error: intentar el mover el tablero al hacer click en una casilla resaltada

**Comment by dieguoin** [comment]
Movimiento separado de estado idle
Fixed
